package io.zipcoder.tc_spring_poll_application.domain;

import jakarta.persistence.*;

/**
 * Option entity - represents a single choice in a poll.
 * 
 * EXAMPLE:
 * Poll: "Favorite Netflix show?"
 * Option: "Stranger Things"
 * 
 * JPA ANNOTATIONS:
 * @Entity - Marks as database table
 * @Id - Primary key
 * @GeneratedValue - Auto-increment ID
 * @Column - Maps to database column
 */
@Entity
public class Option {
    
    /**
     * Primary key - auto-generated by database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "OPTION_ID")
    private Long id;
    
    /**
     * The text value of this option
     * Example: "Stranger Things", "Black Mirror"
     */
    @Column(name = "OPTION_VALUE")
    private String value;
    
    // ==========================================
    // Constructors
    // ==========================================
    
    /**
     * Default constructor - REQUIRED by JPA
     */
    public Option() {
    }
    
    // ==========================================
    // Getters and Setters
    // ==========================================
    
    public Long getId() {
        return id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    public String getValue() {
        return value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    
    @Override
    public String toString() {
        return "Option{id=" + id + ", value='" + value + "'}";
    }
}